from fastapi import FastAPI
from pydantic import BaseModel
import json
import uvicorn
import os

# --- Import your Agents ---
# Assuming your directory structure is correct:
# backend/adk/agents/retriever/retriever_agent.py
# backend/adk/agents/doc_processor/doc_processor_agent.py

# NOTE: You'll need to update your Python path or use relative imports 
# in a real project setup. For this mock, we'll import them assuming they are accessible.

# For testing, we can define the classes directly here or rely on the __main__ block
# from the agent files you provided (if you put them in one file).
# Assuming the agent files are structured as previously discussed:

from adk.agents.retriever.retriever_agent import RetrieverAgent
from adk.agents.doc_processor.doc_processor_agent import DocProcessorAgent

# Define the input schema for the API
class ResearchTopic(BaseModel):
    """The raw user input received by the API."""
    topic: str = "What are the latest findings in multi-agent system reflection?"

# Mock QueryParser output (since we skip the QueryParserAgent for direct testing)
# In a real system, this would be generated by the QueryParserAgent.
def mock_query_parser(topic: str) -> str:
    """Generates the structured JSON expected by the RetrieverAgent."""
    print(f"\n--- MOCK: Simulating QueryParser for topic: '{topic}' ---")
    return json.dumps({
        "core_question": topic,
        "sub_questions": ["What is reflection?", "How is ADK used?"],
        "keywords": topic.split(),
        "boolean_search_queries": [f"({topic}) AND (research OR paper)"],
        "desired_outputs": ["summary"]
    })

# --- FASTAPI Application ---
app = FastAPI(title="ADK Research Pipeline Backend Mock")

@app.post("/run_pipeline")
def run_research_pipeline(input_topic: ResearchTopic):
    """
    Runs the QueryParser -> Retriever -> DocProcessor sequence.
    """
    raw_topic = input_topic.topic

    # 1. MOCK QueryParser Step
    structured_query = mock_query_parser(raw_topic)

    # 2. RetrieverAgent Step (Your Part)
    retriever_agent = RetrieverAgent()
    retriever_output = retriever_agent.run(structured_query)

    # 3. DocProcessorAgent Step (Your Part)
    doc_processor_agent = DocProcessorAgent()
    doc_processor_output = doc_processor_agent.run(retriever_output)

    # Return the processed output, ready for the PaperReaderAgent
    return {
        "status": "Success",
        "message": "Retriever and DocProcessor pipeline complete.",
        "input_topic": raw_topic,
        "final_output_data": json.loads(doc_processor_output)
    }

# Entry point for running the server (as described in your developer instructions)
if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)